### ISSUE TITLE
Training leads to model collapse

### ISSUE THREAD

**Issue by Ricardokevins** [princeton-nlp/SimPO#12]
Hi, Interesting work!  I immediately trained and tested it on my downstream tasks. However, the generated results showed that the model collapsed, outputting a lot of repetition, similar to "Hi Hi Hi Hi Hi". Upon checking the training log, I found that although the margin and accuracy increased, the accept reward and reject reward rapidly decreased.

To rule out the influence of my private dataset and task format, I conducted training on a small subset of the public datasets hiyouga/DPO-En-Zh-20k, and the training dynamics were similar, the reward both decreased rapidly. Have you encountered the similar issues, and how can I resolve it?

Training Argument:
```
batch 128
max_step 1000
simpo_gamma 0.5
beta 2.5
optim paged_adamw_32bit
```

Reward/Reject
![下载 (4)](https://github.com/princeton-nlp/SimPO/assets/43642508/c93f9d6c-ff4b-4299-932f-05d422387c3c)

Reward/Accept
![下载 (2)](https://github.com/princeton-nlp/SimPO/assets/43642508/cdf0d99c-b885-4e70-aeef-6c2ad5fb4bd5)

Reward/Margin
![下载 (3)](https://github.com/princeton-nlp/SimPO/assets/43642508/63ae6bc0-f8f0-44d0-8a8f-64e5d05a1529)

Reward/Accuracy
![下载 (1)](https://github.com/princeton-nlp/SimPO/assets/43642508/8cff1d70-60a0-42af-8654-928403868de0)

Training Loss
![下载 (5)](https://github.com/princeton-nlp/SimPO/assets/43642508/44a3d4cd-c7af-4c8b-959b-5d5d4e8a7d46)

**Comment by yumeng5** [comment]
Hi,

Could you share the model as well as the learning rate you used? When the model degenerates that's usually an implication of the learning rate being too high. I'd try tuning down the learning rate a bit.

Best,
Yu

**Comment by hjh0119** [comment]
I find that SimPO+LoRA performed poorly, maybe full fine-tuning is required.

**Comment by Ricardokevins** [comment]
```
# Model arguments
model_name_or_path: xxxxxxxxxx/PLM/Meta-Llama-3-8B-Instruct
torch_dtype: null
use_flash_attention_2: true

### ddp
ddp_timeout: 180000000
deepspeed: xxxxx/deepspeed/ds_z3_config.json

# Data training arguments
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# SimPOTrainer arguments
bf16: true
beta: 2.5
gamma: 1.4
do_eval: true
evaluation_strategy: steps
eval_steps: 400
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 1.0e-6
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
optim: adamw_torch
output_dir: xxxx/Trained/dev-simpo
run_name: llama-3-8b-instruct-simpo
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
report_to:
- wandb
save_total_limit: 3
seed: 42
warmup_ratio: 0.1
report_to: wandb
run_name: simpo-repro # 可选
```



Hi, I still can not reproduce the result. Above is the training scripts

And following is the result of generate.py
```
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.90it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[{'role': 'user', 'content': "What's the difference between llamas and alpacas?"}, {'role': 'assistant', 'content': 'Both belong to camelids family.\n\nKey differences:\n\n1\\. Size: Llamas tend to grow taller, usually between five feet\n\n(\n15\n\n)&\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n–\n\n'}]
```
